- id: '1612949304955'
  alias: Notification - Internet lost
  description: ''
  trigger:
  - platform: state
    to: 'off'
    entity_id: binary_sensor.internet_connection
    from: 'on'
  condition: []
  action:
  - service: notify.mobile_app_sm_g9860
    data:
      message: Internet connection was lost for a while
  mode: single
- id: '1604939660805'
  alias: Automate - Mute TV on phone call
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sm_g9860_phone_state
    to: ringing
    id: in_call
    from: idle
  - platform: state
    entity_id: sensor.sm_g9860_phone_state
    to: offhook
    id: in_call
    from: idle
  - platform: state
    entity_id: sensor.sm_g9860_phone_state
    to: idle
    id: idle
  condition:
  - condition: state
    entity_id: person.oleksandr
    state: home
  - condition: not
    conditions:
    - condition: device
      device_id: 745d26659dbaf63767790c478ea6288d
      domain: media_player
      entity_id: media_player.sony_bravia_tv
      type: is_off
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: in_call
      sequence:
      - service: media_player.media_pause
        target:
          area_id: gostinaia
      - service: media_player.volume_mute
        data:
          is_volume_muted: true
        target:
          area_id: gostinaia
    - conditions:
      - condition: trigger
        id: idle
      sequence:
      - service: media_player.volume_mute
        data:
          is_volume_muted: false
        target:
          area_id: gostinaia
      - service: media_player.media_play
        target:
          area_id: gostinaia
    default: []
  mode: restart
- id: '1613122603515'
  alias: Alert - On water leak
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 1bd59533a9207101396e64f68d27b3cd
    entity_id: binary_sensor.wleak_toilet
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: b76fdd9ceb5a5353b4402f0207c2ddfa
    entity_id: binary_sensor.wleak_kitchen
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_sm_g9860
    data:
      title: ⚠️ Внимание!
      message: 💧 Water leak detected! {{ trigger.to_state.attributes.friendly_name
        }}
      data:
        channel: Alerts
        importance: max
        color: red
  - service: notify.telegram
    data:
      title: ⚠️ Warning!
      message: 💧 Water leak detected! {{ trigger.to_state.attributes.friendly_name
        }}
  mode: single
- id: '1613122825694'
  alias: Light - Tambur
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: fbd4f134ea563fe78c23306dac509515
    entity_id: binary_sensor.tambur_motion
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: ed7f99e54ea492c992961028be5b150f
    entity_id: light.tambur
    domain: light
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: fbd4f134ea563fe78c23306dac509515
      entity_id: binary_sensor.tambur_motion
      domain: binary_sensor
      for:
        hours: 0
        minutes: 2
        seconds: 0
        milliseconds: 0
  - type: turn_off
    device_id: ed7f99e54ea492c992961028be5b150f
    entity_id: light.tambur
    domain: light
  mode: restart
- id: '1613123012403'
  alias: Light - Corridor
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 36882a38eec93e2f395226698077e7b1
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
    domain: binary_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - type: is_occupied
        condition: device
        device_id: fbd4f134ea563fe78c23306dac509515
        entity_id: binary_sensor.tambur_occupancy
        domain: binary_sensor
      sequence:
      - type: turn_on
        device_id: 4ea55371c191f9a8c3fa6299ab0962e5
        entity_id: light.corridor
        domain: light
      - wait_for_trigger:
        - type: not_opened
          platform: device
          device_id: 36882a38eec93e2f395226698077e7b1
          entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
          domain: binary_sensor
          for:
            hours: 0
            minutes: 2
            seconds: 0
            milliseconds: 0
        continue_on_timeout: false
      - type: turn_off
        device_id: 4ea55371c191f9a8c3fa6299ab0962e5
        entity_id: light.corridor
        domain: light
    default:
    - wait_for_trigger:
      - type: not_opened
        platform: device
        device_id: 36882a38eec93e2f395226698077e7b1
        entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
        domain: binary_sensor
        for:
          hours: 0
          minutes: 2
          seconds: 0
          milliseconds: 0
      continue_on_timeout: false
    - type: turn_off
      device_id: 4ea55371c191f9a8c3fa6299ab0962e5
      entity_id: light.corridor
      domain: light
  mode: restart
- id: '1613123129721'
  alias: Mode - Away
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.mode_away
    to: 'on'
    from: 'off'
  condition: []
  action:
  - scene: scene.away
  mode: single
- id: '1613123951160'
  alias: 'Announce - Twitch '
  description: Twitch stream announces on speaker
  trigger:
  - platform: state
    entity_id: sensor.twitch_guit88man,sensor.twitch_cahchec,sensor.twitch_unclebjorn,sensor.twitch_silvername,sensor.twitch_lenagol0vach
    to: streaming
    for: 0:00:30
  condition:
  - condition: state
    entity_id: person.oleksandr
    state: home
  - condition: not
    conditions:
    - condition: state
      entity_id: input_boolean.mode_sleep
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_guests
      state: 'on'
  action:
  - service: notify.tts_living_room
    data:
      message: Hey! {{ trigger.to_state.attributes.friendly_name }} is started streaming
        {{ trigger.to_state.attributes.game }} on twitch tv
  mode: single
- id: '1613124704897'
  alias: Mode - Sleep
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.mode_sleep
    to: 'on'
  condition: []
  action:
  - scene: scene.sleep
  mode: single
- id: '1613124857885'
  alias: Notification - Sleep mode Off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.wake_up_time
  condition:
  - condition: state
    entity_id: input_boolean.mode_sleep
    state: 'on'
  action:
  - service: notify.mobile_app_sm_g9860
    data:
      title: Sleep Mode
      message: It is time to disable sleep mode.
      data:
        actions:
        - action: SLEEP_MODE_OFF
          title: Turn Off
  - wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: SLEEP_MODE_OFF
    continue_on_timeout: false
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.mode_sleep
  mode: single
- id: '1613125278142'
  alias: Notification - Washing finished
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: e10bdfca6d169338d8cfabbcbb0cd91b
    entity_id: sensor.toilet_plug_electrical_measurement
    domain: sensor
    above: 5
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.washing
  - wait_for_trigger:
    - type: power
      platform: device
      device_id: e10bdfca6d169338d8cfabbcbb0cd91b
      entity_id: sensor.toilet_plug_electrical_measurement
      domain: sensor
      below: 5
      for:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    timeout: 03:00:00
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.washing
  - service: notify.telegram
    data:
      message: Washing has been finished!
  mode: single
- id: '1613163512382'
  alias: Automate - Turn off pc power
  description: ''
  trigger:
  - platform: state
    entity_id: switch.home_pc_wol
    to: 'off'
    from: 'on'
  condition: []
  action:
  - wait_for_trigger:
    - type: power
      platform: device
      device_id: cb089c8a02f25c9ca3753776ff8d0f38
      entity_id: sensor.tz3000_g5xawfcq_ts0121_electrical_measurement
      domain: sensor
      below: 5
  - type: turn_off
    device_id: cb089c8a02f25c9ca3753776ff8d0f38
    entity_id: switch.livingroom_plug
    domain: switch
  mode: single
- id: '1615888678577'
  alias: Alert - Unsufficient space on Nuc drive
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.nuc_used_percent
    above: '95'
    for: 00:01:00
  condition: []
  action:
  - service: notify.mobile_app_sm_g9860
    data:
      title: ⚠️ Warning!
      message: Unsofficient space left on Nuc dive.
      data:
        channel: Alerts
        importance: max
        color: red
  - service: notify.telegram
    data:
      title: ⚠️ Warning!
      message: Unsofficient space left on Nuc dive.
  mode: single
- id: '1625646004211'
  alias: Light - WLED TV
  description: ''
  trigger:
  - platform: state
    entity_id: light.livingroom_tv
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_off
        device_id: 7ecc2fb00b7df9abf5a754e10b4f7488
        entity_id: light.livingroom_tv
        domain: light
      - condition: device
        type: is_on
        device_id: de7fc2bbbf74f16d2d2d84ad41e7f03e
        entity_id: light.wled
        domain: light
      sequence:
      - type: turn_off
        device_id: de7fc2bbbf74f16d2d2d84ad41e7f03e
        entity_id: light.wled
        domain: light
    - conditions:
      - condition: device
        type: is_on
        device_id: 7ecc2fb00b7df9abf5a754e10b4f7488
        entity_id: light.livingroom_tv
        domain: light
      - condition: device
        type: is_off
        device_id: de7fc2bbbf74f16d2d2d84ad41e7f03e
        entity_id: light.wled
        domain: light
      sequence:
      - type: turn_on
        device_id: de7fc2bbbf74f16d2d2d84ad41e7f03e
        entity_id: light.wled
        domain: light
    default: []
  mode: single
- id: '1627630032807'
  alias: Notification - New Wi-Fi device in network
  trigger:
  - platform: event
    event_type: device_tracker_new_device
  action:
  - service: notify.telegram
    data:
      message: 'New device: {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})

        '
      title: New device connected
  mode: single
- id: '1627908810286'
  alias: Notification - Motion in tambur
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: fbd4f134ea563fe78c23306dac509515
    entity_id: binary_sensor.tambur_motion
    domain: binary_sensor
  condition:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.oleksandr
      zone: zone.home
  action:
  - service: notify.telegram
    data:
      message: 'There is motion in tambur right now. '
      title: 🚶‍♂️ Motion detected
  mode: single
- id: '1627909125055'
  alias: Notification - Doorbell or domofon
  description: ''
  trigger:
  - type: sound
    platform: device
    device_id: 9ad718eb888b0a4aad72cd6cb62d6812
    entity_id: binary_sensor.doorbell_chime
    domain: binary_sensor
  - type: locked
    platform: device
    device_id: 9ad718eb888b0a4aad72cd6cb62d6812
    entity_id: binary_sensor.domofon_incoming_call
    domain: binary_sensor
  condition:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.oleksandr
      zone: zone.home
  action:
  - service: notify.telegram
    data:
      message: '{{ trigger.to_state.attributes.friendly_name }} is ringing while you
        are not home'
      title: 🔔 Doorbell or domofon is ringing
  mode: single
- id: '1628081966719'
  alias: Automate - Github Update
  description: ''
  trigger:
  - platform: time
    at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - sat
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /config/scripts/git_update.sh
  mode: single
- id: '1631273652133'
  alias: Light - Toilet
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 228913f20d4a81b754aafc522d776c5e
    entity_id: binary_sensor.toilet_ias_zone
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.mode_sleep
    state: 'off'
  action:
  - type: turn_on
    device_id: 095f00f37cf8b0d04ac9893668ac504b
    entity_id: light.toilet
    domain: light
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: 228913f20d4a81b754aafc522d776c5e
      entity_id: binary_sensor.toilet_ias_zone
      domain: binary_sensor
      for:
        hours: 0
        minutes: 2
        seconds: 0
        milliseconds: 0
  - type: turn_off
    device_id: 095f00f37cf8b0d04ac9893668ac504b
    entity_id: light.toilet
    domain: light
  mode: restart
- id: '1631274616469'
  alias: Light - Kitchen
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 9cde2b2446ba215221b0e9805d7902c0
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: kukhnia
  mode: restart
