- id: '1612949304955'
  alias: Reboot router on internet lost
  description: ''
  trigger:
  - platform: state
    to: 'off'
    entity_id: binary_sensor.internet_connection
    from: 'on'
  condition: []
  action:
  - service: notify.mobile_app_sm_g9860
    data:
      message: Internet connection has been lost. Home Assistant will reoot router
        in 2 minutes.
  - service: timer.start
    data: {}
    entity_id: timer.router_reboot_countdown
  mode: single
- id: '1604939660805'
  alias: Mute TV on phone call
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sm_g9860_phone_state
    to: ringing
  - platform: state
    entity_id: sensor.sm_g9860_phone_state
    to: offhook
  condition:
  - condition: state
    entity_id: person.oleksandr
    state: home
  action:
  - service: media_player.media_pause
    data: {}
    target:
      entity_id: media_player.sony_bravia_tv
      device_id: a3af181ce3e9d1acb3dffaad60232da3
  - service: media_player.volume_mute
    data:
      is_volume_muted: true
    target:
      entity_id: media_player.sony_bravia_tv
      device_id: a3af181ce3e9d1acb3dffaad60232da3
  - wait_for_trigger:
    - platform: state
      entity_id: sensor.sm_g9860_phone_state
      to: idle
  - service: media_player.volume_mute
    data:
      is_volume_muted: false
    target:
      entity_id: media_player.sony_bravia_tv
      device_id: a3af181ce3e9d1acb3dffaad60232da3
  - service: media_player.media_play
    data: {}
    target:
      entity_id: media_player.sony_bravia_tv
      device_id: a3af181ce3e9d1acb3dffaad60232da3
  mode: single
- id: '1613122603515'
  alias: Alert - On water leak
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 1bd59533a9207101396e64f68d27b3cd
    entity_id: binary_sensor.wleak_toilet
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: b76fdd9ceb5a5353b4402f0207c2ddfa
    entity_id: binary_sensor.wleak_kitchen
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_sm_g9860
    data:
      title: ⚠️ Внимание!
      message: 💧 Water leak detected! {{ trigger.to_state.attributes.friendly_name
        }}
      data:
        channel: Alerts
        importance: max
        color: red
  - service: notify.telegram
    data:
      title: ⚠️ Warning!
      message: 💧 Water leak detected! {{ trigger.to_state.attributes.friendly_name
        }}
  mode: single
- id: '1613122825694'
  alias: Light - Tambur
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: fbd4f134ea563fe78c23306dac509515
    entity_id: binary_sensor.tambur_motion
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: ed7f99e54ea492c992961028be5b150f
    entity_id: light.tambur
    domain: light
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: fbd4f134ea563fe78c23306dac509515
      entity_id: binary_sensor.tambur_motion
      domain: binary_sensor
      for:
        hours: 0
        minutes: 2
        seconds: 0
        milliseconds: 0
  - type: turn_off
    device_id: ed7f99e54ea492c992961028be5b150f
    entity_id: light.tambur
    domain: light
  mode: restart
- id: '1613123012403'
  alias: Light - Corridor
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 36882a38eec93e2f395226698077e7b1
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
    domain: binary_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - type: is_occupied
        condition: device
        device_id: fbd4f134ea563fe78c23306dac509515
        entity_id: binary_sensor.tambur_occupancy
        domain: binary_sensor
      sequence:
      - type: turn_on
        device_id: 4ea55371c191f9a8c3fa6299ab0962e5
        entity_id: light.corridor
        domain: light
      - wait_for_trigger:
        - type: not_opened
          platform: device
          device_id: 36882a38eec93e2f395226698077e7b1
          entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
          domain: binary_sensor
          for:
            hours: 0
            minutes: 2
            seconds: 0
            milliseconds: 0
        continue_on_timeout: false
      - type: turn_off
        device_id: 4ea55371c191f9a8c3fa6299ab0962e5
        entity_id: light.corridor
        domain: light
    default:
    - wait_for_trigger:
      - type: not_opened
        platform: device
        device_id: 36882a38eec93e2f395226698077e7b1
        entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
        domain: binary_sensor
        for:
          hours: 0
          minutes: 2
          seconds: 0
          milliseconds: 0
      continue_on_timeout: false
    - type: turn_off
      device_id: 4ea55371c191f9a8c3fa6299ab0962e5
      entity_id: light.corridor
      domain: light
  mode: restart
- id: '1613123129721'
  alias: Mode - Away
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.mode_away
    to: 'on'
    from: 'off'
  condition: []
  action:
  - scene: scene.away
  mode: single
- id: '1613123951160'
  alias: 'Announce - Twitch '
  description: Twitch stream announces on speaker
  trigger:
  - platform: state
    entity_id:
    - sensor.twitch_guit88man
    - sensor.twitch_cahchec
    - sensor.twitch_unclebjorn
    to: streaming
    for: 0:00:30
  condition:
  - condition: state
    entity_id: person.oleksandr
    state: home
  action:
  - service: notify.tts_living_room
    data:
      message: Hey! {{ trigger.to_state.attributes.friendly_name }} is started streaming
        {{ trigger.to_state.attributes.game }} on twitch tv
  mode: single
- id: '1613124704897'
  alias: Mode - Sleep
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.mode_sleep
    to: 'on'
  condition: []
  action:
  - scene: scene.sleep
  - service: automation.turn_off
    entity_id: automation.announce_twitch
  - wait_for_trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
    continue_on_timeout: false
  - service: automation.turn_on
    data: {}
    entity_id: automation.announce_twitch
  mode: single
- id: '1613124857885'
  alias: Notification - Sleep mode Off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.wake_up_time
  condition:
  - condition: state
    entity_id: input_boolean.mode_sleep
    state: 'on'
  action:
  - service: notify.mobile_app_sm_g9860
    data:
      title: Sleep Mode
      message: It is time to disable sleep mode.
      data:
        actions:
        - action: SLEEP_MODE_OFF
          title: Turn Off
  - wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: SLEEP_MODE_OFF
    continue_on_timeout: false
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.mode_sleep
  mode: single
- id: '1613125278142'
  alias: Notification - Washing finished
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: e10bdfca6d169338d8cfabbcbb0cd91b
    entity_id: sensor.toilet_plug_electrical_measurement
    domain: sensor
    above: 5
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.washing
  - wait_for_trigger:
    - type: power
      platform: device
      device_id: e10bdfca6d169338d8cfabbcbb0cd91b
      entity_id: sensor.toilet_plug_electrical_measurement
      domain: sensor
      below: 5
      for:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    timeout: 03:00:00
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.washing
  - service: notify.telegram
    data:
      message: Washing has been finished!
  mode: single
- id: '1613163512382'
  alias: Turn off pc power
  description: ''
  trigger:
  - platform: state
    entity_id: switch.home_pc_wol
    to: 'off'
    from: 'on'
  condition: []
  action:
  - wait_for_trigger:
    - type: power
      platform: device
      device_id: cb089c8a02f25c9ca3753776ff8d0f38
      entity_id: sensor.livingroom_plug_electrical_measurement
      domain: sensor
      below: 5
  - type: turn_off
    device_id: cb089c8a02f25c9ca3753776ff8d0f38
    entity_id: switch.livingroom_plug
    domain: switch
  mode: single
- id: '1613845078667'
  alias: Light - Toilet
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: d200b3ca3a4c78c0c78a317b8fa18051
    entity_id: binary_sensor.ble_motion_nightlight
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 095f00f37cf8b0d04ac9893668ac504b
    entity_id: light.toilet_light
    domain: light
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: d200b3ca3a4c78c0c78a317b8fa18051
      entity_id: binary_sensor.ble_motion_nightlight
      domain: binary_sensor
  - type: turn_off
    device_id: 095f00f37cf8b0d04ac9893668ac504b
    entity_id: light.toilet_light
    domain: light
  mode: restart
