default_config:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

homeassistant:
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret ip_host

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
