homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config

frontend:
  themes: !include_dir_merge_named themes

default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.1
    - 192.168.88.200

logger:
  default: error
  logs: {}
#    homeassistant.components.mobile_app.webhook: debug
#    custom_components.ble_monitor: debug
