wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true
  #manual_ip:
  #  static_ip: 192.168.88.197
  #  gateway: 192.168.88.1
  #  subnet: 255.255.255.0

  ap:
    ssid: ${device_name}_hotspot
    password: !secret wifi_pass
