substitutions:
  device_name: kitchen-shades
  friendly_name: Kitchen Shades
  speed: 300 steps/s # Set the speed of the motor
  lc: cover_left
  ls: stepper_left
  ls_pina: D0 # Swap these \_ coil a
  ls_pinb: D1 # Swap these /
  ls_pinc: D2 # Swap these \_ coil b
  ls_pind: D3 # Swap these /
  rc: cover_right
  rs: stepper_right
  rs_pina: D4
  rs_pinb: D5
  rs_pinc: D6
  rs_pind: D8


packages:
  base: !include common/base.yaml
  wifi: !include common/wifi.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: True
  on_boot:
    - priority: -200.0
      then:
    # Set steppers to global variables
      - stepper.report_position: 
          id: $ls
          position: !lambda return id(${ls}_position);
      - stepper.report_position: 
          id: $rs
          position: !lambda return id(${rs}_position);
    # Set stepper to global variable
      - stepper.set_target: 
          id: $ls
          target: !lambda return id(${ls}_position);
      - stepper.set_target: 
          id: $rs
          target: !lambda return id(${rs}_position);          
      - if: # If blind is Closed
          condition:
            - lambda: 'return id(${ls}_position) == 0;'
          then: # Publish state etc.
            - cover.template.publish:
                id: $lc
                state: CLOSED
                current_operation: IDLE
      - if: # If blind is Open
          condition:
            - lambda: 'return id(${ls}_position) == id(${ls}_endstop);'
          then: # Publish state etc.
            - cover.template.publish:
                id: $lc
                state: OPEN
                current_operation: IDLE
      - if: # If blind is Neither
          condition:
            - lambda: 'return (id(${ls}_position) != 0) && (id(${ls}_position) != id(${ls}_endstop));'
          then: #  # Publish state etc.
            - cover.template.publish:
                id: $lc
                position: !lambda 'return (float(float(id($ls).current_position) / float(id(${ls}_endstop))));' 
                current_operation: IDLE

stepper:
  - platform: uln2003
    id: $ls
    pin_a: $ls_pina
    pin_b: $ls_pinb
    pin_c: $ls_pinc
    pin_d: $ls_pind
    max_speed: ${speed}
    sleep_when_done: True
    acceleration: inf
    deceleration: inf
  - platform: uln2003
    id: $rs
    pin_a: $rs_pina
    pin_b: $rs_pinb
    pin_c: $rs_pinc
    pin_d: $rs_pind
    max_speed: ${speed}
    sleep_when_done: True
    acceleration: inf
    deceleration: inf

globals:
  - id: ${lc}_state # Boolean to store OPEN/CLOSED state
    type: bool
    restore_value: True
    initial_value: '0'

  - id: ${rc}_state # Boolean to store OPEN/CLOSED state
    type: bool
    restore_value: True
    initial_value: '0'

  - id: ${ls}_position # Integer for storing the stepper position in case of reboot
    type: int
    restore_value: True
    initial_value: '0'

  - id: ${rs}_position # Integer for storing the stepper position in case of reboot
    type: int
    restore_value: True
    initial_value: '0'

  - id: ${ls}_endstop # Variable for storing ENDSTOP (how far to move stepper)
    type: int
    restore_value: True
    initial_value: '1000'

  - id: ${rs}_endstop # Variable for storing ENDSTOP (how far to move stepper)
    type: int
    restore_value: True
    initial_value: '1000'

  - id: settingmode # Integer for Setup Mode
    type: int
    restore_value: no
    initial_value: '0'

binary_sensor:
  - platform: gpio
    pin:
      number: D7 # Connect Button to D7 and GND
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    internal: True
    on_click:
    - min_length: 50ms
      max_length: 500ms
      then: # Short press to OPEN/CLOSE blinds and also for setting up
        - if: # If settings variable is on
            condition:
              - lambda: 'return id(settingmode) != 0;'
            then: # Enter Setting Mode
              - script.execute: setupbutton
            else:
              - if: # If blind is closed
                  condition:
                    - lambda: 'return id(state_right) == 0;'
                  then: # Open blind
                    - cover.open: right
                  else: # Close blind
                    - cover.close: right
    - min_length: 1000ms
      max_length: 3000ms
      then: # Long press to Enter Setting Mode
        - logger.log: "Entered Settings Mode"
        - globals.set:
            id: settingmode
            value:  '1'

select:
  - platform: template
    id: activeshade
    name: "Setup Shade"
    entity_category: config
    optimistic: true
    options:
      - "none"
      - left
      - right
    initial_option: "none"
    on_value:
      then:
        - if:
            condition:
              - lambda: 'return id(activeshade).state != "none";'
            then:
              - logger.log:
                  format: "Entered Settings Mode for the %s shade"
                  args: ["x.c_str()"]
              - globals.set:
                  id: settingmode
                  value:  '1'
            else:
              - logger.log: "Exiting Settings Mode"
              - globals.set:
                  id: settingmode
                  value:  '0'
button:
  - platform: template
    name: ${friendly_name} Setup Button # Switch to replicate the Physical Button
    id: hasetup
    entity_category: config
    on_press:
      - if: # If settings variable is on
          condition:
            - lambda: 'return id(settingmode) != 0;'
          then: # Enter Setting Mode
            - script.execute: setupbutton

cover:
  - platform: template
    name: $friendly_name Right
    id: $lc
    open_action:
      then:
        - logger.log: "Opening"
        - stepper.set_target: # Send stepper to endstop
            id: $mystepper
            target: !lambda return id(${ls}_endstop);
        - while:
            condition:
              lambda: 'return id($mystepper).current_position != id(endstop_right);'
            then:
              - cover.template.publish:
                  id: right
                  position: !lambda 'return (float(float(id($mystepper).current_position) / float(id(endstop_right))));' 
                  current_operation: OPENING
              - delay: 1000 ms
        - globals.set: # Set global to current position
            id: ${mystepper}_global
            value: !lambda return id($mystepper).current_position; 
        - globals.set: # Set toggle to OPEN (No need for 'optimistic mode')
            id: state_right
            value: '1'
        - cover.template.publish:
            id: right
            state: OPEN 
            current_operation: IDLE
    close_action:
      then:
        - logger.log: "Closing"
        - stepper.set_target: # Send stepper to 0
            id: $mystepper
            target: '0'
        - while:
            condition:
              lambda: 'return id($mystepper).current_position != 0;'
            then:
              - cover.template.publish:
                  id: right
                  position: !lambda 'return (float(float(id($mystepper).current_position) / float(id(endstop_right))));' 
                  current_operation: CLOSING
              - delay: 1000 ms
        - globals.set: # Set global to current position
            id: ${mystepper}_global
            value: !lambda return id($mystepper).current_position; 
        - globals.set: # Set toggle to CLOSED (No need for 'optimistic mode')
            id: state_right
            value: '0'
        - cover.template.publish:
            id: right
            state: CLOSED
            current_operation: IDLE
    position_action:
      then:
        - stepper.set_target:
            id: $mystepper
            target: !lambda return int(id(endstop_right) * pos);
        - while:
            condition:
              lambda: 'return id($mystepper).current_position != int(id(endstop_right) * pos);'
            then:
              - cover.template.publish:
                  id: right
                  position: !lambda 'return (float(float(id($mystepper).current_position) / float(id(endstop_right))));' 
              - delay: 1000 ms
        - globals.set: # Set global to current position
            id: ${mystepper}_global
            value: !lambda return id($mystepper).current_position; 
        - cover.template.publish:
            id: right
            position: !lambda 'return (float(float(id($mystepper).current_position) / float(id(endstop_right))));' 
            current_operation: IDLE
    stop_action:
      then:
        - stepper.set_target:
            id: $mystepper
            target: !lambda return id($mystepper).current_position;
        - globals.set: # Set global to current position
            id: ${mystepper}_global
            value: !lambda return id($mystepper).current_position;
        - cover.template.publish:
            id: right
            position: !lambda 'return (float(float(id($mystepper).current_position) / float(id(endstop_right))));' 
            current_operation: IDLE
    has_position: true
    device_class: shade

script:
  - id: setupbutton
    then:
      - if:
          condition:
            - lambda: 'return (id(settingmode) == 3);'
          then:
            - logger.log: "Pressed Setup Button: Mode 3"
            - stepper.set_target: # Set Stepper position
                id: $mystepper
                target: !lambda return id($mystepper).current_position;
            - globals.set: # Set Endstop Variable
                id: endstop_right
                value: !lambda return id($mystepper).current_position;
            - globals.set: # Set Global stepper position
                id: ${mystepper}_global
                value: !lambda return id($mystepper).current_position;
            - globals.set: # Reset Setting Mode
                id: settingmode
                value:  '0'
            - globals.set: # Set toggle to Open
                id: state_right
                value: '1'
            - cover.template.publish:
                id: right
                state: OPEN 
                current_operation: IDLE
            - logger.log: "Exiting Setting Mode"
      - if:
          condition:
            - lambda: 'return (id(settingmode) == 2);'
          then:
            - logger.log: "Pressed Setup Button: Mode 2"
            - stepper.report_position: # Reset Stepper position to 0
                id: $mystepper
                position: '0'
            - stepper.set_target: # Reset Stepper position to 0
                id: $mystepper
                target: '0'
            - globals.set: # Move stepper to 0 (doesn't move it's already there!)
                id: ${mystepper}_global
                value: '0'
            - stepper.set_target: # Reset Stepper position to 72000
                id: $mystepper
                target: '72000'
            - globals.set: # Advance setup to next mode
                id: settingmode
                value:  '3'
      - if:
          condition:
            - lambda: 'return (id(settingmode) == 1);'
          then:
            - logger.log: "Pressed Setup Button: Mode 1"
            - stepper.report_position: # Set Stepper position to 72000, makes it move to 0 (Closed)
                id: $mystepper
                position: '72000'
            - globals.set: # Advance setup to next mode
                id: settingmode
                value:  '2'

sensor:
  - <<: !include common/uptime.yaml
  - <<: !include common/rssi.yaml