esphome:
  name: nodemcu_multisensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Multisensor Fallback Hotspot"
    password: !secret esp_pass

captive_portal:


web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      filters:
        - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 15.1 -> 16.3
          - 21.5 -> 22.4
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
      filters:
        - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 22 -> 28
          - 25 -> 30
    address: 0x76
    i2c_id: bus_a
    update_interval: 60s

i2c:
 - id: bus_a
   sda: 4             #D2
   scl: 5             #D1
   scan: True

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D8
    num_leds: 41
    rgb_order: GRB
    name: "Cabinet LEDS"
    
switch:
  - platform: gpio
    pin: D5
    id: pc_sw
    name: "PC-SW"
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: pc_sw
    
