substitutions:
  device_name: office
  friendly_name: Office

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi.yaml

esphome:
  name: $device_name
  platform: ESP8266
  board: nodemcuv2

sensor:
  - <<: !include common/uptime.yaml
  - <<: !include common/rssi.yaml
  - platform: bme280
    temperature:
      name: $friendly_name Temperature
      filters:
        - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 15.1 -> 16.3
          - 21.5 -> 22.4
    pressure:
      name: $friendly_name Pressure
    humidity:
      name: $friendly_name Humidity"
      filters:
        - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 22 -> 28
          - 25 -> 30
    address: 0x76
    i2c_id: bus_a
    update_interval: 60s

i2c:
 - id: bus_a
   sda: 4             #D2
   scl: 5             #D1
   scan: True

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D8
    num_leds: 41
    rgb_order: GRB
    name: $friendly_name Desk Light
    
switch:
  - platform: gpio
    pin: D5
    id: pc_sw
    name: $friendly_name PC Switch
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: pc_sw
    
