substitutions:
  device_name: office_light

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  #manual_ip:
    #static_ip: 192.168.88.187
    #gateway: 192.168.88.1
    #subnet: 255.255.255.0
  ap:
    ssid: ${device_name}_hotspot
    password: !secret esp_pass

web_server:
  port: 80

logger:

api:
  password: !secret esp_pass

ota:
  password: !secret esp_pass

status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    name: ${device_name}_sw
    pin: GPIO04
    id: switch_1
    on_state:
      then:
        - light.toggle: light_1
        
light:
  - platform: binary
    id: light_1
    name: "Office Light"
    output: light_output

output:
  - platform: gpio
    id: light_output
    pin: GPIO12

sensor:
  - platform: uptime
    name: ${device_name}_uptime
  - platform: wifi_signal
    name: ${device_name}_rssi
    update_interval: 60s
