recorder:
  db_url: sqlite:////config/home-assistant_v2.db
  purge_keep_days: 7
  auto_purge: true
  include:
    domains:
      - switch
      - light
      - media-player
      - vacuum
      - climate
      - sensor
      - binary_sensor
      - cover
      - input_boolean
      - input_text
    entities: {}
    entity_globs: {}
  exclude:
    entities:
      - sensor.home_assistant_v2_db
      - sensor.date_time

sensor:
  - platform: filesize
    file_paths:
      - "/config/home-assistant_v2.db"
