recorder:
  db_url: sqlite:////config/home-assistant_v2.db
  purge_keep_days: 7
  auto_purge: true
  include:
    domains:
      - binary_sensor
      - climate
      - cover
      - device_tracker
      - input_boolean
      - input_text
      - light
      - media_player
      - script
      - sensor
      - switch
      - vacuum
      - update
    entities:
      - alarm_control_panel.alarmo
      - group.safety
    entity_globs: {}
  exclude:
    entities:
      - sensor.nuc_uptime
    entity_globs:
      - sensor.home_assistant_v2_db_*
