sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: disk_free
        arg: /
  - platform: rest
    value_template: "{{ value_json }}"
    resource: http://192.168.88.200:61208/api/3/uptime
    name: Nuc Uptime
    scan_interval: 600

binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "Internet Connection"
    count: 2
    scan_interval: 60

homeassistant:
  customize:
    sensor.nuc_uptime:
      icon: mdi:clock
