sensor:
  - platform: twitch
    entity_namespace: twitch
    client_id: !secret twitch_client_id
    client_secret: !secret twitch_secret
    token: !secret twitch_token
    scan_interval: 120
    channels:
      - guit88man
      - cahchec
      - UncleBjorn
      - SilverName
      - lenagol0vach
      - verni_shavermy

homeassistant:
  customize:
    sensor.twitch_lenagol0vach:
      pronunciation: LenaGolovach
    sensor.twitch_guit88man:
      pronunciation: guitman
    sensor.twitch_cahchec:
      pronunciation: sanches
    sensor.twitch_verni_shavermy:
      pronunciation: phill

script:
  cast_twitch_stream:
    alias: Cast twitch stream
    description: "Cast twitch stream to defined chromecast device"
    fields:
      stream:
        description: "The sensor tracking stream status"
    sequence:
      - service: media_extractor.play_media
        data:
          entity_id: media_player.kd_55xf8505
          media_content_id: "https://twitch.tv/ {{ stream }}"
          media_content_type: video
    mode: single
    icon: "mdi:twitch"
